- .gitignore
- package-lock.json
- package.json
- ts/src/checker.ts
- ts/src/config.ts
- ts/src/github.ts
- ts/src/package-json-file.ts
- tsconfig.json
Add `nyc` and `codecov`.
Also support Node 6. For that, some code changes were needed:
- Target ES5
- Not use `Array#includes()` or `Object#values()`
- Not use the `URL` class or `promisify()`
> chore: add code coverage support

- .circleci/config.yml
It turns out that `jsgl` runs with Node 4 as well as 6+. Run tests for
Node 4 too.
> chore: run circleci for node 4 too

- README.md
- ts/src/checker.ts
- ts/src/cli.ts
- ts/test/checker-test.ts
Factor out the default handlers for CLI output so they can be reused as part
of the library (i.e. for Gulp or similar systems.)
> Refactor CLI logic for easier use from Gulp.

- README.md
- ts/src/checker.ts
It should've been exported from the beginning. Otherwise client code
can't use the github-related APIs when using this package as a library.
> chore: export `GitHubRepository` from checker.ts

- README.md
- package-lock.json
- package.json
- ts/src/config.ts
- ts/test/config-test.ts
Sometimes we may want to add comments in the config file. E.g. in a
package whitelist, comment on why a certain package should be
whitelisted, or comment on related github issues, etc.
Also more changes:
- Add unit tests for config.ts
- Exclude test files from coverage stats
- Update dependencies' versions
> feat: allow comments in config json file

- ts/src/checker.ts
- ts/test/checker-test.ts
It used to be emitted only for GitHub repos but it'll be more sane to
make it symmetric between local and github repos.
> feat: emit 'package.json' event also for local repos

- .circleci/config.yml
By default, CircleCI doesn't run for tag pushes, which prevents NPM
publish from being triggered.
Let the tests run for version tag pushes so they trigger NPM publish.
> chore: let CI run for version tags

- package.json
The draft release note is in the GitHub UI.
I'm making this a semver minor change because there's an additional
event emitted from
https://github.com/google/js-green-licenses/pull/16. Please let me know
if you disagree.
> chore: publish v0.3.0

- .circleci/config.yml
- package.json
Hopefully this will fix the auto-NPM-publishing. Currently the `prepare`
phase fails.
> chore: make CI run as non-root

- .circleci/config.yml
This fixes npm-auto-publishing.
> fix: `npm publish` must be done after `npm install`.

- README.md
And also move the greenkeeper badge to the end of the badge list.
> chore: fix typos.

- .gitignore
- package-lock.json
- package.json
- ts/src/checker.ts
- ts/src/config.ts
- ts/test/checker-test.ts
- ts/test/config-test.ts
- ts/test/github-test.ts
- tsconfig.json
And use new ES module interop feature.
> chore: upgrade typescript to 2.7.1

- package-lock.json
- package.json
After we upgraded `spdx-satisfies` and `spdx-correct`, we now support
SPDX 3.0 license lists:
https://spdx.org/news/news/2018/01/license-list-30-released
Draft release notes are in
https://github.com/google/js-green-licenses/releases/tag/untagged-f216e2851745a55bc189
> chore: release v0.5.0

- .circleci/config.yml
> chore: define regexp only once in circleci config

- package-lock.json
- package.json
- ts/test/checker-test.ts
Test code related to `proxyquire` had to be changed a little bit because
with `proxyquire` 2.0.1, the old trick doesn't work for some reason.
> chore: update packages

- .circleci/config.yml
- package.json
BREAKING CHANGE: Drop support for Node.js 6.x which reaching EOL in a
couple of weeks.
> build!: drop support for Node 6

- package-lock.json
- package.json
- src/checker.ts
- src/config.ts
- test/fixtures.ts
Since this only works for nodejs 8 and up, we can drop pify and just use `util.promisify`.
> refactor: prefer promisify to pify

- README.md
Just makes a few changes to the badges:
- Drops the `devDependency` badge
- Uses the shield style for the CircleCI badge
- Drops the `greenkeeper` badge we aren't using anymore
- Adds the gts code style badge
> docs: update the README badges

- src/checker.ts
- src/package-json-file.ts
- test/checker-test.ts
Adds support for private packages, without name and version. 
It's common for a monorepo project to have a private root package.json, like:
```
{
"private": true,
"devDependencies": {
},
"workspaces": [
"packages/*"
]
}
```
It breaks license verification currently, because such package doesn't have name and version. 
My PR fixes that, by accepting such package.json file, and using `private` license if it's not specified
> feat: support private packages

- src/checker.ts
- test/checker-test.ts
For local packages, follow local package references.
Fixes: https://github.com/google/js-green-licenses/issues/96
> feat: support local paths

- .circleci/config.yml
- .eslintignore
- .eslintrc.json
- .prettierignore
- .prettierrc.js
- package-lock.json
- package.json
- src/checker.ts
- src/cli.ts
- src/config.ts
- src/github.ts
- src/package-json-file.ts
- test/checker-test.ts
- test/config-test.ts
- test/github-test.ts
This drops CI for node 8, upgrades to gts2, and makes a few other quality of life improvements.
> build: drop support for node.js 8

- src/checker.ts
- test/checker-test.ts
As far as I'm aware only all caps spelling (with alternative UNLICENCED spelling) is allowed (see: [validate-npm-package-license.js](https://github.com/kemitchell/validate-npm-package-license.js/blob/master/index.js#L39)).
This resolves that issue, the library correctly treats UNLICENSED as non-green (all copyright retained). I've added a test case for that as well.
> fix: Added support for the UNLICENSED NPM magic value (fixes #113)
